#!/usr/bin/env bash
set -euo pipefail

# ─── Remove Ralph Worktrees ──────────────────────────────────
# Finds all ralph worktrees created by ralph.sh, and for each:
#   1. Commits any uncommitted changes (excluding log files)
#   2. Copies .claude-ralph-log*.txt into .claude/ralph-logs/<branch>/ in the main repo
#   3. Removes the worktree
#   4. Pushes the branch and creates a PR on GitHub
#
# Usage:
#   ./remove_ralph_worktrees.sh              # Process all ralph worktrees
#   ./remove_ralph_worktrees.sh --dry-run    # Preview without making changes

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
WORKTREE_DIR="$REPO_ROOT/.claude/worktrees"
LOG_DIR="$REPO_ROOT/.claude/ralph-logs"
BASE_BRANCH="main"
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run) DRY_RUN=true; shift ;;
    *)         echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# ─── Find ralph worktrees ────────────────────────────────────
# ralph.sh creates worktrees at .claude/worktrees/ralph-*
declare -a WORKTREE_PATHS=()
declare -a WORKTREE_BRANCHES=()

while IFS= read -r line; do
  if [[ "$line" =~ ^worktree\ (.*/ralph-.+)$ ]]; then
    wt_path="${BASH_REMATCH[1]}"
  elif [[ "$line" =~ ^branch\ refs/heads/(.+)$ && -n "${wt_path:-}" ]]; then
    WORKTREE_PATHS+=("$wt_path")
    WORKTREE_BRANCHES+=("${BASH_REMATCH[1]}")
    wt_path=""
  elif [[ -z "$line" ]]; then
    wt_path=""
  fi
done < <(git -C "$REPO_ROOT" worktree list --porcelain)

if [[ ${#WORKTREE_PATHS[@]} -eq 0 ]]; then
  echo "No ralph worktrees found."
  exit 0
fi

echo "Found ${#WORKTREE_PATHS[@]} ralph worktree(s)"
echo "────────────────────────────────────────"

for i in "${!WORKTREE_PATHS[@]}"; do
  wt_path="${WORKTREE_PATHS[$i]}"
  branch="${WORKTREE_BRANCHES[$i]}"

  echo ""
  echo "═══════════════════════════════════════════════════════"
  echo "  Worktree: ${wt_path}"
  echo "  Branch:   ${branch}"
  echo "═══════════════════════════════════════════════════════"

  if [[ ! -d "$wt_path" ]]; then
    echo "  Directory missing, skipping."
    continue
  fi

  if $DRY_RUN; then
    cd "$wt_path"
    uncommitted=$(git status --porcelain -- . ':!.claude-ralph-log*.txt' 2>/dev/null | head -5)
    log_files=$(ls .claude-ralph-log*.txt 2>/dev/null || true)
    commits_ahead=$(git rev-list --count "${BASE_BRANCH}..HEAD" 2>/dev/null || echo "0")
    echo "  [dry-run] Commits ahead of ${BASE_BRANCH}: ${commits_ahead}"
    if [[ -n "$uncommitted" ]]; then
      echo "  [dry-run] Has uncommitted changes (excluding logs):"
      echo "$uncommitted" | sed 's/^/    /'
    else
      echo "  [dry-run] No uncommitted changes (excluding logs)"
    fi
    if [[ -n "$log_files" ]]; then
      echo "  [dry-run] Log files to copy: ${log_files}"
    fi
    echo "  [dry-run] Would remove worktree, push branch, and create PR"
    cd "$REPO_ROOT"
    continue
  fi

  # ─── 1. Commit any uncommitted changes (excluding log files) ──
  cd "$wt_path"

  # Check for changes excluding ralph log files
  if [[ -n $(git status --porcelain -- . ':!.claude-ralph-log*.txt' 2>/dev/null) ]]; then
    echo "  Committing uncommitted changes..."
    git add -- . ':!.claude-ralph-log*.txt'
    git commit -m "${branch}

Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>"
    echo "  Committed."
  else
    echo "  No uncommitted changes (excluding logs)."
  fi

  # ─── 2. Copy log files into main repo ─────────────────────────
  # Use the branch name (slashes replaced with dashes) as the log subfolder
  log_subdir="${LOG_DIR}/${branch//\//-}"
  log_files=(.claude-ralph-log*.txt)
  if [[ -e "${log_files[0]}" ]]; then
    mkdir -p "$log_subdir"
    cp .claude-ralph-log*.txt "$log_subdir/"
    echo "  Copied log files to ${log_subdir}"
  else
    echo "  No log files found."
  fi

  # ─── 3. Check commits, push, and create PR ────────────────────
  commits_ahead=$(git rev-list --count "${BASE_BRANCH}..HEAD" 2>/dev/null || echo "0")

  if [[ "$commits_ahead" -gt 0 ]]; then
    echo "  ${commits_ahead} commit(s) on branch. Pushing..."
    git push -u origin "$branch"

    # Build a commit summary for the PR body
    commit_log=$(git log --oneline "${BASE_BRANCH}..HEAD" | sed 's/^/- /')

    pr_title="[Ralph] ${branch#ralph/}"
    pr_body="$(cat <<EOF
## Auto-generated by Ralph Loop

**Branch:** ${branch}

### Commits
${commit_log}

---
Generated autonomously by Claude Code via ralph.sh.
Review carefully before merging.
EOF
)"

    # Create PR (ignore error if it already exists)
    gh pr create \
      --base "$BASE_BRANCH" \
      --head "$branch" \
      --title "${pr_title:0:72}" \
      --body "$pr_body" \
      2>&1 || echo "  PR creation failed (may already exist)"

    echo "  PR created/exists for branch: ${branch}"
  else
    echo "  No commits ahead of ${BASE_BRANCH}. Skipping push/PR."
  fi

  # ─── 4. Remove the worktree ───────────────────────────────────
  cd "$REPO_ROOT"
  echo "  Removing worktree..."
  git worktree remove "$wt_path" --force
  echo "  Worktree removed."

  echo "  Done with ${branch}."
done

echo ""
echo "════════════════════════════════════════════"
echo "  All ralph worktrees processed."
echo "════════════════════════════════════════════"

# Summary
echo ""
echo "Remaining worktrees:"
git worktree list
echo ""
echo "Open Ralph PRs:"
gh pr list --author "@me" --search "Ralph" 2>/dev/null || true

if [[ -d "$LOG_DIR" ]]; then
  echo ""
  echo "Ralph logs saved to: ${LOG_DIR}"
  echo "(Not committed — review and commit manually if desired)"
fi
